-- MySQL Script generated by MySQL Workbench
-- Sat Dec 21 02:59:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema concrete
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concrete
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concrete` DEFAULT CHARACTER SET utf8 ;
USE `concrete` ;

-- -----------------------------------------------------
-- Table `concrete`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concrete`.`users` ;

CREATE TABLE IF NOT EXISTS `concrete`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NULL,
  `status` TINYINT(1) NULL,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concrete`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concrete`.`orders` ;

CREATE TABLE IF NOT EXISTS `concrete`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `users_id` INT NOT NULL,
  `deliveryDateTime` DATETIME NULL,
  `status` ENUM('confirm', 'cancel', 'pay') NULL,
  `tel` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `concrete`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concrete`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concrete`.`items` ;

CREATE TABLE IF NOT EXISTS `concrete`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `price` DECIMAL(8,2) NULL,
  `cube` VARCHAR(20) NULL,
  `installment` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concrete`.`deliverycharges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concrete`.`deliverycharges` ;

CREATE TABLE IF NOT EXISTS `concrete`.`deliverycharges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `price` DECIMAL(8,2) NULL,
  `area` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concrete`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concrete`.`item` ;

CREATE TABLE IF NOT EXISTS `concrete`.`item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `orders_id` INT NOT NULL,
  `items_id` INT NULL,
  `deliverycharges_id` INT NULL,
  `price` DECIMAL(8,2) NULL,
  `list` VARCHAR(45) NULL,
  `discount` DECIMAL(8,2) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_item_orders_idx` (`orders_id` ASC),
  INDEX `fk_item_items1_idx` (`items_id` ASC),
  INDEX `fk_item_deliverycharges1_idx` (`deliverycharges_id` ASC),
  UNIQUE INDEX `orders_id_UNIQUE` (`orders_id` ASC),
  CONSTRAINT `fk_item_orders`
    FOREIGN KEY (`orders_id`)
    REFERENCES `concrete`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_items1`
    FOREIGN KEY (`items_id`)
    REFERENCES `concrete`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_deliverycharges1`
    FOREIGN KEY (`deliverycharges_id`)
    REFERENCES `concrete`.`deliverycharges` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concrete`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concrete`.`location` ;

CREATE TABLE IF NOT EXISTS `concrete`.`location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `orders_id` INT NOT NULL,
  `latitude` DECIMAL(8,2) NULL,
  `latitude_copy1` DECIMAL(8,2) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_location_orders1_idx` (`orders_id` ASC),
  CONSTRAINT `fk_location_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `concrete`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
